services:
  logs:
    container_name: docker-logs
    image: vivekanandkumar98/docker-logs-node:latest
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

    # updated
