name: Node-Js-CICD

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      # 1. Checkout the branch
      - uses: actions/checkout@v4

      # 2. Setup Node.js with Cache
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # 3. Install Dependencies
      - name: Install Dependencies
        run: npm install

      # 4. Login to docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.HUB_USERNAME}}
          password: ${{secrets.HUB_PASSWORD}}

      # 5. Build and push Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{secrets.HUB_USERNAME}}/docker-logs-node:latest

      # 6. Login to AWS, pull Image and Run Container
      - name: Deploy to aws
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{secrets.AWS_HOST}}
          username: ${{secrets.AWS_USER}}
          key: ${{secrets.AWS_KEY}}
          script: |
            docker pull ${{secrets.HUB_USERNAME}}/docker-logs-node:latest
            docker stop docker-logs-node || true
            docker rm docker-logs-node || true
            docker run -d --name docker-logs-node -p 3000:3000 ${{secrets.HUB_USERNAME}}/docker-logs-node:latest

      # 6.  Completed
      - name: ✅ Done
        run: echo "Actions Completed!"
