name: Node-Js-CICD

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      # 1. Checkout the branch
      - uses: actions/checkout@v4

      # 2. Setup Node.js with Cache
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # 3. Install Dependencies
      - name: Install Dependencies
        run: npm install

      # 4. Build Docker Image
      - name: Build Docker Image
        run: docker build -t docker-log-img .

      # 5. Login to docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.HUB_USERNAME}}
          password: ${{secrets.HUB_PASSWORD}}

      # 6. Push Image on Docker Hub
      - name: Push Image on Docker Hub
        run: docker push docker-log-img:latest

      # Completed
      - name: ✅ Done
        run: echo "Actions Completed!"
